from io import BytesIO
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak

def build_report(case):
    buf=BytesIO(); doc=SimpleDocTemplate(buf,pagesize=letter,rightMargin=.65*inch,leftMargin=.65*inch,topMargin=.55*inch,bottomMargin=.55*inch)
    styles=getSampleStyleSheet(); styles.add(ParagraphStyle(name='DarkTitle',parent=styles['Title'],textColor=colors.HexColor('#8be9fd'),fontName='Helvetica-Bold',fontSize=22,spaceAfter=8)); styles.add(ParagraphStyle(name='Small',parent=styles['BodyText'],fontSize=8,textColor=colors.HexColor('#52606d')))
    story=[Paragraph('TRUTHFORGE',styles['DarkTitle']),Paragraph('AI RESPONSE FORENSIC REPORT',styles['Heading2']),Spacer(1,10)]
    meta=[['CASE ID',case['case_id']],['TIMESTAMP',case['timestamp']],['MODEL',case['model_version']],['VERDICT',case['verdict']],['HALLUCINATION RISK',f"{case['overall_risk']:.1f}%"],['RELIABILITY ESTIMATE',f"{100-case['overall_risk']:.1f} / 100"]]
    t=Table(meta,colWidths=[1.7*inch,4.8*inch]); t.setStyle(TableStyle([('BACKGROUND',(0,0),(0,-1),colors.HexColor('#e8eef2')),('GRID',(0,0),(-1,-1),.3,colors.HexColor('#b8c4cc')),('FONTNAME',(0,0),(-1,-1),'Helvetica'),('FONTNAME',(0,0),(0,-1),'Helvetica-Bold'),('VALIGN',(0,0),(-1,-1),'TOP'),('PADDING',(0,0),(-1,-1),7)])); story += [t,Spacer(1,16),Paragraph('QUESTION',styles['Heading3']),Paragraph(case['question'],styles['BodyText']),Spacer(1,8),Paragraph('AI RESPONSE',styles['Heading3']),Paragraph(case['response'].replace('&','&amp;'),styles['BodyText']),Spacer(1,14)]
    story += [Paragraph('FORENSIC SIGNALS',styles['Heading3'])]
    signals=case.get('result',{}).get('signals',{}); st=Table([[k,str(v)] for k,v in signals.items()],colWidths=[4.8*inch,1.2*inch]); st.setStyle(TableStyle([('GRID',(0,0),(-1,-1),.3,colors.HexColor('#b8c4cc')),('BACKGROUND',(0,0),(-1,0),colors.HexColor('#e8eef2')),('PADDING',(0,0),(-1,-1),6)])); story += [st,Spacer(1,12),Paragraph('LIMITATIONS',styles['Heading3']),Paragraph('TRUTHFORGE estimates hallucination risk from learned linguistic and semantic patterns. It does not guarantee factual correctness and does not perform external fact verification.',styles['BodyText']),Spacer(1,12),Paragraph('Generated by TRUTHFORGE local forensic engine.',styles['Small'])]
    doc.build(story); return buf.getvalue()
